### ISSUE TITLE
Speccycle gets stuck on one player 

### ISSUE THREAD

**Issue by avatar7008** [CuzIm1Tigaaa/Spectator#18] opened 2023-09-24 01:49 UTC
Occasionally speccycle gets stuck on one particular player. Doesn't matter if I specify random or alphabetical. 

Server: Paper 1.20.1

It cycles through all users normally for a while, then gets stuck on a random player and doesn't cycle anymore. Is there a limited duration on how long it can cycle for?

**Comment by CuzIm1Tigaaa** [comment] 2023-09-28 19:27
> Is there a limited duration on how long it can cycle for?
No, there should not be a limit. Sadly I know about that issue but did not find a solution for it. I am very sorry for that.

But can you give me more information about your players online? Like how many were on when this happens? Has a player quit or died before? This would help me a lot!
Also what is your configuration in the `Cycle` section?

**Comment by CuzIm1Tigaaa** [comment] 2023-12-16 16:36
Speccycle was rewritten entirely and I could not reproduce this issue. Should be fixed in the upcoming update.

**Closed by CuzIm1Tigaaa** 2023-12-16 16:36 UTC
